server:
  port: 8080

token-general:
  security:
    config:
      issuer: CPE
      key: LostToken!3.141516

app:
  security:
    config:
      enabled: true
      path:
        public-path: /api/public/customer/**
        protected-path: /api/protected/customer/**
        private-path: /api/private/customer/**